projects:
  digayuta:
    schemaPath: graphql/schema.json
    includes:
      - "y"
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: .
